
# General
CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_JSON_LIBRARY=y
CONFIG_REBOOT=y

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_FPU=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Heap and stacks
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# LTE link controller
CONFIG_LTE_LINK_CONTROL=y
CONFIG_LTE_LC_PSM_MODULE=y
CONFIG_LTE_LC_EDRX_MODULE=y

# AT commands interface
# CONFIG_AT_HOST_LIBRARY=y
# CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_CJSON_LIB=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# Network
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=y
CONFIG_NET_IPV4=y
CONFIG_NET_CONNECTION_MANAGER=y

# AWS IoT library
CONFIG_AWS_IOT=y
CONFIG_AWS_IOT_APP_VERSION="v1.0.0"
# CONFIG_AWS_IOT_CLIENT_ID_STATIC="359746167121867"
CONFIG_AWS_IOT_BROKER_HOST_NAME="a1pex7b5gbosrz-ats.iot.us-east-1.amazonaws.com"
CONFIG_AWS_IOT_TOPIC_UPDATE_DELTA_SUBSCRIBE=y
CONFIG_AWS_IOT_TOPIC_GET_ACCEPTED_SUBSCRIBE=y
CONFIG_AWS_IOT_TOPIC_GET_REJECTED_SUBSCRIBE=y
CONFIG_AWS_IOT_DEVICE_ID_USE_HW_ID=y
CONFIG_AWS_FOTA_DOWNLOAD_SECURITY_TAG=30

# MQTT helper library
CONFIG_MQTT_HELPER=y
CONFIG_MQTT_HELPER_SEC_TAG=30
CONFIG_MQTT_HELPER_LAST_WILL=y
CONFIG_MQTT_HELPER_STACK_SIZE=4096
CONFIG_MQTT_HELPER_LOG_LEVEL_OFF=y

# MQTT - Maximum MQTT keepalive timeout specified by AWS IoT Core
CONFIG_MQTT_KEEPALIVE=1200
CONFIG_MQTT_CLEAN_SESSION=y

CONFIG_HW_ID_LIBRARY=y
CONFIG_HW_ID_LIBRARY_SOURCE_IMEI=y

# One of the below should be n
CONFIG_AWS_IOT_USE_EDRX=y
CONFIG_AWS_IOT_USE_LTE_POWER_OFF=n

# CONFIG_AWS_IOT_LOG_LEVEL_DBG=y
# CONFIG_AWS_FOTA_LOG_LEVEL_DBG=y

#RTT 
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

# POWER MANAGEMENT

CONFIG_PM_DEVICE=y
CONFIG_POWEROFF=y

# Enable UART driver
CONFIG_SERIAL=n

# Enable console
CONFIG_CONSOLE=n

CONFIG_AT_HOST_LIBRARY=n
